In [40]:
import numpy as np
import pandas as pd


In [42]:
np.set_printoptions(suppress=True)

In [54]:
np.set_printoptions(suppress=True)

In [2]:
data = pd.read_excel('/Users/yingzhedong/Desktop/图神经网络合集/df_csi300_total_five_year_f.xlsx',index_col=0)
data

000001.SZ  000002.SZ  000009.SZ  000027.SZ  000039.SZ  000046.SZ  \
Symbols                                                                        
2015-01-05  10.411111  11.948872   7.826626   6.895378  16.361078   9.352264   
2015-01-06  10.255109  11.508102   7.826626   6.907493  16.235193   8.844569   
2015-01-07  10.060174  11.403920   8.056290   7.186220  15.813210   9.307729   
2015-01-08   9.722246  10.891025   8.068371   6.895378  15.354186   8.773314   
2015-01-09   9.800201  10.778828   7.844758   6.653007  15.124716   8.773314   
...               ...        ...        ...        ...        ...        ...   
2020-12-30  19.200001  28.379999   7.580000   6.180000  14.680000   3.280000   
2020-12-31  19.340000  28.700001   7.530000   6.090000  14.990000   3.280000   
2021-01-04  18.600000  27.780001   7.790000   6.250000  15.570000   3.220000   
2020-12-31  19.340000  28.700001   7.530000   6.090000  14.990000   3.280000   
2021-01-04  18.600000  27.780001   7.790000   6.250000  15.570000   3.220000   

            000060.SZ  000061.SZ  000063.SZ  000069.SZ  ...  601988.SS.5  \
Symbols                                                 ...                
2015-01-05   6.375500  13.114096  15.352232   7.291382  ...   2308454847   
2015-01-06   6.601454  12.561207  16.240513   7.003787  ...   2312726022   
2015-01-07   6.686946  12.503009  15.917511   6.910742  ...   1548575455   
2015-01-08   6.522063  12.347811  16.143600   6.640064  ...   1489272605   
2015-01-09   6.351069  12.027719  15.788330   6.547018  ...   2277619375   
...               ...        ...        ...        ...  ...          ...   
2020-12-30   4.840000   7.070000  33.439999   6.790000  ...     79605410   
2020-12-31   4.820000   7.050000  33.650002   7.090000  ...    110906068   
2021-01-04   4.960000   7.260000  34.330002   6.890000  ...    121250317   
2020-12-31   4.820000   7.050000  33.650002   7.090000  ...    110906068   
2021-01-04   4.960000   7.260000  34.330002   6.890000  ...    121250317   

            601989.SS.5  601991.SS.5  601992.SS.5  601998.SS.5  603000.SS.5  \
Symbols                                                                       
2015-01-05    837202913    235866017    172969934    337368242     14467510   
2015-01-06    868557636    156192152     89135498    289390330     19819866   
2015-01-07    457456599    104222910     73868232    180969317     13776728   
2015-01-08    456533433     74716497     66345244    202660638     10623170   
2015-01-09    509497900     72752743    116668302    258676854     12858144   
...                 ...          ...          ...          ...          ...   
2020-12-30     73548511     57712090     13824461     12020513      6793664   
2020-12-31    156774438     48039160     15429798     20925884      9242020   
2021-01-04    173038254     40505875     25966261     19995047      9984269   
2020-12-31    156774438     48039160     15429798     20925884      9242020   
2021-01-04    173038254     40505875     25966261     19995047      9984269   

            603885.SS.5  603993.SS.5  002450.SZ.5  600074.SS.5  
Symbols                                                         
2015-01-05          NaN     91532514          NaN          NaN  
2015-01-06          NaN    169487109          NaN          NaN  
2015-01-07          NaN    124705686          NaN          NaN  
2015-01-08          NaN     74194596          NaN          NaN  
2015-01-09          NaN     94735206          NaN          NaN  
...                 ...          ...          ...          ...  
2020-12-30    7280394.0    771099043          NaN          NaN  
2020-12-31   12706489.0    735785546          NaN          NaN  
2021-01-04   10345040.0    765332022          NaN          NaN  
2020-12-31   12706489.0    735785546          NaN          NaN  
2021-01-04   10345040.0    765332022          NaN          NaN  

[1463 rows x 1794 columns]

In [32]:
#数据的列名
data.columns

Index(['000001.SZ', '000002.SZ', '000009.SZ', '000027.SZ', '000039.SZ',
       '000046.SZ', '000060.SZ', '000061.SZ', '000063.SZ', '000069.SZ',
       ...
       '601988.SS.5', '601989.SS.5', '601991.SS.5', '601992.SS.5',
       '601998.SS.5', '603000.SS.5', '603885.SS.5', '603993.SS.5',
       '002450.SZ.5', '600074.SS.5'],
      dtype='object', length=1794)

In [15]:
#列名的截取
cut_stock_name=[]
for i in range(len(data.columns)):
    cut_stock_name.append(data.columns[i][:9])

In [17]:
#独立的股票代号
set_cut_stock_name = set(cut_stock_name)
len(set_cut_stock_name)

299

In [36]:
#构建input矩阵
stock_matrix = np.zeros((len(data),len(set_cut_stock_name),6))
stock_matrix

array([[[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        ...,
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        ...,
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        ...,
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]],

       ...,

       [[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        ...,
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        .

In [20]:
#矩阵shape
stock_matrix.shape

(1463, 299, 6)

In [31]:
set_cut_stock_name = cut_stock_name[0:299]

In [33]:
len(set_cut_stock_name)

299

In [37]:
for i in range(len(data)):
    print(i/len(data))
    for j in range(len(set_cut_stock_name)):
        flag=0
        for k in range(data.shape[1]):
            if set_cut_stock_name[j] in data.columns[k]:
                stock_matrix[i,j,flag] = data.iloc[i,k]
                flag+=1
stock_matrix

0.0
0.000683526999316473
0.001367053998632946
0.002050580997949419
0.002734107997265892
0.003417634996582365
0.004101161995898838
0.004784688995215311
0.005468215994531784
0.006151742993848257
0.00683526999316473
0.007518796992481203
0.008202323991797676
0.00888585099111415
0.009569377990430622
0.010252904989747095
0.010936431989063569
0.01161995898838004
0.012303485987696514
0.012987012987012988
0.01367053998632946
0.014354066985645933
0.015037593984962405
0.01572112098427888
0.016404647983595352
0.017088174982911826
0.0177717019822283
0.01845522898154477
0.019138755980861243
0.019822282980177717
0.02050580997949419
0.021189336978810664
0.021872863978127138
0.022556390977443608
0.02323991797676008
0.023923444976076555
0.02460697197539303
0.025290498974709502
0.025974025974025976
0.026657552973342446
0.02734107997265892
0.028024606971975393
0.028708133971291867
0.02939166097060834
0.03007518796992481
0.030758714969241284
0.03144224196855776
0.03212576896787423
0.032809295967190705
0.03

0.2822966507177033
0.28298017771701983
0.2836637047163363
0.2843472317156528
0.28503075871496925
0.2857142857142857
0.2863978127136022
0.28708133971291866
0.2877648667122351
0.2884483937115516
0.2891319207108681
0.2898154477101845
0.29049897470950103
0.2911825017088175
0.291866028708134
0.29254955570745045
0.2932330827067669
0.2939166097060834
0.29460013670539986
0.2952836637047163
0.2959671907040328
0.2966507177033493
0.29733424470266573
0.29801777170198224
0.2987012987012987
0.2993848257006152
0.30006835269993165
0.3007518796992481
0.3014354066985646
0.30211893369788106
0.3028024606971975
0.303485987696514
0.3041695146958305
0.30485304169514693
0.30553656869446344
0.3062200956937799
0.3069036226930964
0.30758714969241285
0.3082706766917293
0.3089542036910458
0.30963773069036227
0.3103212576896787
0.31100478468899523
0.3116883116883117
0.31237183868762813
0.31305536568694464
0.3137388926862611
0.3144224196855776
0.31510594668489406
0.3157894736842105
0.316473000683527
0.31715652768284

0.5727956254272044
0.5734791524265208
0.5741626794258373
0.5748462064251538
0.5755297334244702
0.5762132604237867
0.5768967874231032
0.5775803144224196
0.5782638414217361
0.5789473684210527
0.579630895420369
0.5803144224196856
0.5809979494190021
0.5816814764183186
0.582365003417635
0.5830485304169515
0.583732057416268
0.5844155844155844
0.5850991114149009
0.5857826384142174
0.5864661654135338
0.5871496924128503
0.5878332194121668
0.5885167464114832
0.5892002734107997
0.5898838004101162
0.5905673274094326
0.5912508544087491
0.5919343814080656
0.592617908407382
0.5933014354066986
0.5939849624060151
0.5946684894053315
0.595352016404648
0.5960355434039645
0.596719070403281
0.5974025974025974
0.5980861244019139
0.5987696514012304
0.5994531784005468
0.6001367053998633
0.6008202323991798
0.6015037593984962
0.6021872863978127
0.6028708133971292
0.6035543403964456
0.6042378673957621
0.6049213943950786
0.605604921394395
0.6062884483937115
0.606971975393028
0.6076555023923444
0.608339029391661
0.

0.8701298701298701
0.8708133971291866
0.8714969241285031
0.8721804511278195
0.872863978127136
0.8735475051264525
0.8742310321257689
0.8749145591250854
0.8755980861244019
0.8762816131237184
0.8769651401230348
0.8776486671223513
0.8783321941216679
0.8790157211209843
0.8796992481203008
0.8803827751196173
0.8810663021189337
0.8817498291182502
0.8824333561175667
0.8831168831168831
0.8838004101161996
0.8844839371155161
0.8851674641148325
0.885850991114149
0.8865345181134655
0.8872180451127819
0.8879015721120984
0.8885850991114149
0.8892686261107313
0.8899521531100478
0.8906356801093643
0.8913192071086808
0.8920027341079972
0.8926862611073137
0.8933697881066303
0.8940533151059467
0.8947368421052632
0.8954203691045797
0.8961038961038961
0.8967874231032126
0.8974709501025291
0.8981544771018455
0.898838004101162
0.8995215311004785
0.9002050580997949
0.9008885850991114
0.9015721120984279
0.9022556390977443
0.9029391660970608
0.9036226930963773
0.9043062200956937
0.9049897470950102
0.9056732740943

array([[[1.04111109e+01, 1.11250000e+01, 1.13056002e+01, 1.08332996e+01,
         1.10972004e+01, 4.11902845e+08],
        [1.19488716e+01, 1.49099998e+01, 1.52900000e+01, 1.45000000e+01,
         1.45400000e+01, 6.56083570e+08],
        [7.82662582e+00, 7.99383020e+00, 7.99383020e+00, 7.99383020e+00,
         7.99383020e+00, 0.00000000e+00],
        ...,
        [2.91351461e+00, 3.21000004e+00, 3.21000004e+00, 2.94000006e+00,
         2.94000006e+00, 9.15325140e+07],
        [           nan,            nan,            nan,            nan,
                    nan,            nan],
        [           nan,            nan,            nan,            nan,
                    nan,            nan]],

       [[1.02551088e+01, 1.09582996e+01, 1.13818998e+01, 1.07986002e+01,
         1.10068998e+01, 3.11964681e+08],
        [1.15081024e+01, 1.43599997e+01, 1.49899998e+01, 1.40500002e+01,
         1.46000004e+01, 3.34634683e+08],
        [7.82662582e+00, 7.99383020e+00, 7.99383020e+00, 7.993830

In [55]:
stock_matrix

array([[[1.04111109e+01, 1.11250000e+01, 1.13056002e+01, 1.08332996e+01,
         1.10972004e+01, 4.11902845e+08],
        [1.19488716e+01, 1.49099998e+01, 1.52900000e+01, 1.45000000e+01,
         1.45400000e+01, 6.56083570e+08],
        [7.82662582e+00, 7.99383020e+00, 7.99383020e+00, 7.99383020e+00,
         7.99383020e+00, 0.00000000e+00],
        ...,
        [2.91351461e+00, 3.21000004e+00, 3.21000004e+00, 2.94000006e+00,
         2.94000006e+00, 9.15325140e+07],
        [           nan,            nan,            nan,            nan,
                    nan,            nan],
        [           nan,            nan,            nan,            nan,
                    nan,            nan]],

       [[1.02551088e+01, 1.09582996e+01, 1.13818998e+01, 1.07986002e+01,
         1.10068998e+01, 3.11964681e+08],
        [1.15081024e+01, 1.43599997e+01, 1.49899998e+01, 1.40500002e+01,
         1.46000004e+01, 3.34634683e+08],
        [7.82662582e+00, 7.99383020e+00, 7.99383020e+00, 7.993830

In [63]:
stock_matrix.shape

(1463, 299, 6)

In [44]:
np.save("stock_price_matrix.npy",stock_matrix)

In [65]:
#构建新的股票矩阵
stock_matrix_adjust = stock_matrix[:,:,1:]

In [66]:
stock_matrix_adjust

array([[[1.11250000e+01, 1.13056002e+01, 1.08332996e+01, 1.10972004e+01,
         4.11902845e+08],
        [1.49099998e+01, 1.52900000e+01, 1.45000000e+01, 1.45400000e+01,
         6.56083570e+08],
        [7.99383020e+00, 7.99383020e+00, 7.99383020e+00, 7.99383020e+00,
         0.00000000e+00],
        ...,
        [3.21000004e+00, 3.21000004e+00, 2.94000006e+00, 2.94000006e+00,
         9.15325140e+07],
        [           nan,            nan,            nan,            nan,
                    nan],
        [           nan,            nan,            nan,            nan,
                    nan]],

       [[1.09582996e+01, 1.13818998e+01, 1.07986002e+01, 1.10068998e+01,
         3.11964681e+08],
        [1.43599997e+01, 1.49899998e+01, 1.40500002e+01, 1.46000004e+01,
         3.34634683e+08],
        [7.99383020e+00, 7.99383020e+00, 7.99383020e+00, 7.99383020e+00,
         0.00000000e+00],
        ...,
        [3.30332994e+00, 3.45667005e+00, 3.23333001e+00, 3.35999990e+00,
        

In [67]:
np.save("stock_price_matrix_adjust.npy",stock_matrix_adjust)