In [2]:
import numpy as np
import pandas as pd
np.set_printoptions(suppress=True)

In [3]:
data = pd.read_excel('/Users/yingzhedong/Desktop/图神经网络合集/df_csi300_total_five_year_f.xlsx',index_col=0)
data

000001.SZ  000002.SZ  000009.SZ  000027.SZ  000039.SZ  000046.SZ  \
Symbols                                                                        
2015-01-05  10.411111  11.948872   7.826626   6.895378  16.361078   9.352264   
2015-01-06  10.255109  11.508102   7.826626   6.907493  16.235193   8.844569   
2015-01-07  10.060174  11.403920   8.056290   7.186220  15.813210   9.307729   
2015-01-08   9.722246  10.891025   8.068371   6.895378  15.354186   8.773314   
2015-01-09   9.800201  10.778828   7.844758   6.653007  15.124716   8.773314   
...               ...        ...        ...        ...        ...        ...   
2020-12-30  19.200001  28.379999   7.580000   6.180000  14.680000   3.280000   
2020-12-31  19.340000  28.700001   7.530000   6.090000  14.990000   3.280000   
2021-01-04  18.600000  27.780001   7.790000   6.250000  15.570000   3.220000   
2020-12-31  19.340000  28.700001   7.530000   6.090000  14.990000   3.280000   
2021-01-04  18.600000  27.780001   7.790000   6.250000  15.570000   3.220000   

            000060.SZ  000061.SZ  000063.SZ  000069.SZ  ...  601988.SS.5  \
Symbols                                                 ...                
2015-01-05   6.375500  13.114096  15.352232   7.291382  ...   2308454847   
2015-01-06   6.601454  12.561207  16.240513   7.003787  ...   2312726022   
2015-01-07   6.686946  12.503009  15.917511   6.910742  ...   1548575455   
2015-01-08   6.522063  12.347811  16.143600   6.640064  ...   1489272605   
2015-01-09   6.351069  12.027719  15.788330   6.547018  ...   2277619375   
...               ...        ...        ...        ...  ...          ...   
2020-12-30   4.840000   7.070000  33.439999   6.790000  ...     79605410   
2020-12-31   4.820000   7.050000  33.650002   7.090000  ...    110906068   
2021-01-04   4.960000   7.260000  34.330002   6.890000  ...    121250317   
2020-12-31   4.820000   7.050000  33.650002   7.090000  ...    110906068   
2021-01-04   4.960000   7.260000  34.330002   6.890000  ...    121250317   

            601989.SS.5  601991.SS.5  601992.SS.5  601998.SS.5  603000.SS.5  \
Symbols                                                                       
2015-01-05    837202913    235866017    172969934    337368242     14467510   
2015-01-06    868557636    156192152     89135498    289390330     19819866   
2015-01-07    457456599    104222910     73868232    180969317     13776728   
2015-01-08    456533433     74716497     66345244    202660638     10623170   
2015-01-09    509497900     72752743    116668302    258676854     12858144   
...                 ...          ...          ...          ...          ...   
2020-12-30     73548511     57712090     13824461     12020513      6793664   
2020-12-31    156774438     48039160     15429798     20925884      9242020   
2021-01-04    173038254     40505875     25966261     19995047      9984269   
2020-12-31    156774438     48039160     15429798     20925884      9242020   
2021-01-04    173038254     40505875     25966261     19995047      9984269   

            603885.SS.5  603993.SS.5  002450.SZ.5  600074.SS.5  
Symbols                                                         
2015-01-05          NaN     91532514          NaN          NaN  
2015-01-06          NaN    169487109          NaN          NaN  
2015-01-07          NaN    124705686          NaN          NaN  
2015-01-08          NaN     74194596          NaN          NaN  
2015-01-09          NaN     94735206          NaN          NaN  
...                 ...          ...          ...          ...  
2020-12-30    7280394.0    771099043          NaN          NaN  
2020-12-31   12706489.0    735785546          NaN          NaN  
2021-01-04   10345040.0    765332022          NaN          NaN  
2020-12-31   12706489.0    735785546          NaN          NaN  
2021-01-04   10345040.0    765332022          NaN          NaN  

[1463 rows x 1794 columns]

In [72]:
#close, high, low, open, volume
stock_price_data = np.load("stock_price_matrix_adjust.npy")
stock_price_data

array([[[1.11250000e+01, 1.13056002e+01, 1.08332996e+01, 1.10972004e+01,
         4.11902845e+08],
        [1.49099998e+01, 1.52900000e+01, 1.45000000e+01, 1.45400000e+01,
         6.56083570e+08],
        [7.99383020e+00, 7.99383020e+00, 7.99383020e+00, 7.99383020e+00,
         0.00000000e+00],
        ...,
        [3.21000004e+00, 3.21000004e+00, 2.94000006e+00, 2.94000006e+00,
         9.15325140e+07],
        [           nan,            nan,            nan,            nan,
                    nan],
        [           nan,            nan,            nan,            nan,
                    nan]],

       [[1.09582996e+01, 1.13818998e+01, 1.07986002e+01, 1.10068998e+01,
         3.11964681e+08],
        [1.43599997e+01, 1.49899998e+01, 1.40500002e+01, 1.46000004e+01,
         3.34634683e+08],
        [7.99383020e+00, 7.99383020e+00, 7.99383020e+00, 7.99383020e+00,
         0.00000000e+00],
        ...,
        [3.30332994e+00, 3.45667005e+00, 3.23333001e+00, 3.35999990e+00,
        

In [73]:
stock_price_data.shape

(1463, 299, 5)

In [77]:
#以5对空值进行补全
ad_sample_data = stock_price_data
ad_sample_data[np.isnan(ad_sample_data)] = 5

In [78]:
ad_sample_data

array([[[1.11250000e+01, 1.13056002e+01, 1.08332996e+01, 1.10972004e+01,
         4.11902845e+08],
        [1.49099998e+01, 1.52900000e+01, 1.45000000e+01, 1.45400000e+01,
         6.56083570e+08],
        [7.99383020e+00, 7.99383020e+00, 7.99383020e+00, 7.99383020e+00,
         0.00000000e+00],
        ...,
        [3.21000004e+00, 3.21000004e+00, 2.94000006e+00, 2.94000006e+00,
         9.15325140e+07],
        [5.00000000e+00, 5.00000000e+00, 5.00000000e+00, 5.00000000e+00,
         5.00000000e+00],
        [5.00000000e+00, 5.00000000e+00, 5.00000000e+00, 5.00000000e+00,
         5.00000000e+00]],

       [[1.09582996e+01, 1.13818998e+01, 1.07986002e+01, 1.10068998e+01,
         3.11964681e+08],
        [1.43599997e+01, 1.49899998e+01, 1.40500002e+01, 1.46000004e+01,
         3.34634683e+08],
        [7.99383020e+00, 7.99383020e+00, 7.99383020e+00, 7.99383020e+00,
         0.00000000e+00],
        ...,
        [3.30332994e+00, 3.45667005e+00, 3.23333001e+00, 3.35999990e+00,
        

In [79]:
Pearson_stock_price = np.zeros((ad_sample_data.shape[1],ad_sample_data.shape[1]))
Pearson_stock_price.shape

(299, 299)

In [80]:
#(N,N) - Pearson
for i in range(ad_sample_data.shape[1]):
    x = ad_sample_data[:,i,0]
    for j in range(ad_sample_data.shape[1]):
        y = ad_sample_data[:,j,0]
        pccs = np.corrcoef(x, y)
        Pearson_stock_price[i,j] = pccs[0,1]
Pearson_stock_price

array([[ 1.        ,  0.48774958, -0.11249275, ...,  0.02584884,
                nan,         nan],
       [ 0.48774958,  1.        , -0.4896556 , ...,  0.28275634,
                nan,         nan],
       [-0.11249275, -0.4896556 ,  1.        , ..., -0.0788581 ,
                nan,         nan],
       ...,
       [ 0.02584884,  0.28275634, -0.0788581 , ...,  1.        ,
                nan,         nan],
       [        nan,         nan,         nan, ...,         nan,
                nan,         nan],
       [        nan,         nan,         nan, ...,         nan,
                nan,         nan]])

In [81]:
#因为如果x=[5,5,5]这种没有变化的数据（填充数据）。则pearson的结果为nan，所以这里先按0处理
Pearson_stock_price[np.isnan(Pearson_stock_price)] = 0

In [82]:
Pearson_stock_price

array([[ 1.        ,  0.48774958, -0.11249275, ...,  0.02584884,
         0.        ,  0.        ],
       [ 0.48774958,  1.        , -0.4896556 , ...,  0.28275634,
         0.        ,  0.        ],
       [-0.11249275, -0.4896556 ,  1.        , ..., -0.0788581 ,
         0.        ,  0.        ],
       ...,
       [ 0.02584884,  0.28275634, -0.0788581 , ...,  1.        ,
         0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ]])

In [83]:
np.save("Pearson_stock_price.npy",Pearson_stock_price)